--- #YAML:1.0
name: make2build
version: 0.18_02
author:
  - Steven Schubiger <sts@accognoscere.org>
abstract: create a Build.PL derived from Makefile.PL
license: unknown
generated_by: Module::Build version 0.2611, without YAML.pm
